# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_maingui.ui'
#
# Created: Sat Aug 17 20:45:11 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(569, 545)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/course_icon_gre.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.word_widget = QtGui.QWidget(self.centralwidget)
        self.word_widget.setGeometry(QtCore.QRect(0, 0, 561, 171))
        self.word_widget.setObjectName("word_widget")
        self.wordedit = QtGui.QLineEdit(self.word_widget)
        self.wordedit.setGeometry(QtCore.QRect(60, 10, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(12)
        self.wordedit.setFont(font)
        self.wordedit.setObjectName("wordedit")
        self.label = QtGui.QLabel(self.word_widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.searchButton = QtGui.QToolButton(self.word_widget)
        self.searchButton.setGeometry(QtCore.QRect(480, 10, 41, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/search-button-green-icon 32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton.setIcon(icon1)
        self.searchButton.setIconSize(QtCore.QSize(32, 32))
        self.searchButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.searchButton.setObjectName("searchButton")
        self.wordlist = QtGui.QListWidget(self.word_widget)
        self.wordlist.setGeometry(QtCore.QRect(60, 60, 411, 101))
        self.wordlist.setObjectName("wordlist")
        self.meaning_widget = QtGui.QWidget(self.centralwidget)
        self.meaning_widget.setGeometry(QtCore.QRect(0, 180, 561, 271))
        self.meaning_widget.setObjectName("meaning_widget")
        self.meaningtextEdit = QtGui.QTextEdit(self.meaning_widget)
        self.meaningtextEdit.setGeometry(QtCore.QRect(10, 0, 551, 271))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.meaningtextEdit.setFont(font)
        self.meaningtextEdit.setReadOnly(True)
        self.meaningtextEdit.setObjectName("meaningtextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 569, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAbout_me = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/user-info-icon 48x48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_me.setIcon(icon2)
        self.actionAbout_me.setObjectName("actionAbout_me")
        self.actionPervious = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Previous 32x32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPervious.setIcon(icon3)
        self.actionPervious.setObjectName("actionPervious")
        self.actionNext = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/next 48x48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext.setIcon(icon4)
        self.actionNext.setObjectName("actionNext")
        self.toolBar.addAction(self.actionPervious)
        self.toolBar.addAction(self.actionNext)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAbout_me)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PyGRE", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Word", None, QtGui.QApplication.UnicodeUTF8))
        self.searchButton.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_me.setText(QtGui.QApplication.translate("MainWindow", "About pyGRE", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_me.setToolTip(QtGui.QApplication.translate("MainWindow", "About this app", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_me.setStatusTip(QtGui.QApplication.translate("MainWindow", "About this app ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_me.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPervious.setText(QtGui.QApplication.translate("MainWindow", "pervious", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPervious.setToolTip(QtGui.QApplication.translate("MainWindow", "perviously searched word", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPervious.setStatusTip(QtGui.QApplication.translate("MainWindow", "view words previosly searched", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPervious.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Left", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setText(QtGui.QApplication.translate("MainWindow", "next", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setToolTip(QtGui.QApplication.translate("MainWindow", "words searched later", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setStatusTip(QtGui.QApplication.translate("MainWindow", "view words later searched", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNext.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Right", None, QtGui.QApplication.UnicodeUTF8))

import iconresource_rc
